# Generated by Django 4.2.6 on 2023-10-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="content",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="board",
            name="writer",
            field=models.CharField(max_length=25),
        ),
    ]
