# Generated by Django 4.2.6 on 2023-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_alter_board_content_alter_board_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
